on:
  release:
    types: [created]
name: Release
jobs:
  release:
    name: Relese
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install dependencies apt
        run: sudo apt-get install lua5.1 luarocks npm
      - name: Install dependencies npm
        run: npm i love.js
      - name: Build
        run: ./build.sh web
          
#   artifacts:
#     needs: [build]
#     name: Upload artifacts to release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Upload artifacts to release
#         uses: Roang-zero1/github-upload-release-artifacts-action@master
#         with:
#           args:
#           - target/enjoy.love
#           - target/enjoy-win.zip
#           - target/enjoy-web.zip
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Deploy web to github pages
        with:
          build-dir: target/enjoy-web
          deploy-branch: gh-pages
        uses:  NickSchimek/deploy_jamstack_action@main

